# -*- mode: ruby -*-
# # vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "chef/centos-6.5"
    
    config.vm.provision "shell", path: "labsetup.sh"

    config.vm.define "redismaster" do |redismaster|
        redismaster.vm.box = "chef/centos-6.5"
        redismaster.vm.hostname = "redismaster"
        redismaster.vm.network "private_network", ip: "192.168.150.5"
    end

    config.vm.define "redisslave" do |redisslave|
        redisslave.vm.box = "chef/centos-6.5"
        redisslave.vm.hostname = "redisslave"
        redisslave.vm.network "private_network", ip: "192.168.150.10"
    end

end
